default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: shipit_development

test:
  <<: *default
  database: shipit_test

production:
  <<: *default
  database: postgres
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] %>